### ISSUE TITLE
欲しいAPIリスト

### ISSUE THREAD

**Issue by ayanogami** [jphacks/B_2109#52]
既存のもの含めて書きます．
* 本登録API
* しおりID設定API
* 現在のユーザの本リスト取得API　レスポンス： (ユーザID，[本ID，タイトル，サムネ画像，値段，ISBN,　ページ数，　 進捗，しおりID，ステータス])
* 目標設定API 　
* 進捗実績取得API　レスポンス：　(ユーザID,開始日，終了日，ページ数，時間) 
* 累計進捗実績取得API　レスポンス：　(ユーザID,開始日，終了日，ページ数，時間)
* 対戦相手リスト取得API　レスポンス：　（[ユーザID, 名前，[readingな本のタイトル]，先週のページ数実績]）
* ランキング取得API ([順位, ユーザID, ページ数])
* 本単位の進捗取得API レスポンス： (ユーザID,本ID，進捗（パーセント）)

**Comment by zenizeni0918** [comment]
・対戦相手取得API　レスポンス：（対戦相手名, 対戦相手の達成度）
・しおりの放置状況取得API　レスポンス：（しおりID, 最終利用日）
